name:                replay
version:             0.1.0.0
github:              "githubuser/replay"
license:             BSD3
author:              "Claudio Bley"
maintainer:          "claudio.bley@gmail.com"
copyright:           "2019 Claudio Bley"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/replay#readme>

dependencies:
- base >= 4.7 && < 5
- brick >= 0.47.1 && < 0.48
- vty >= 5.15 && < 6
- process
- microlens
- microlens-th
- mtl
- optparse-applicative
- text
- unix

library:
  source-dirs: src

executables:
  replay:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - replay

tests:
  repeat-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - replay
