name: Update niv

on:
  workflow_dispatch:
  schedule:
    # every monday at 4am UTC
    - cron: '0 4 * * mon'

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v16
      with:
         nix_path: nixpkgs=./nix/nixpkgs.nix
    # https://github.com/nmattia/niv/issues/280
    - run: nix-shell --run "niv update" -p niv
    - uses: cachix/cachix-action@v10
      with:
        name: cbley
        extraPullNames: pre-commit-hooks
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        skipPush: true
    - run: nix-build --no-out-link
    - run: nix-shell --run "pre-commit run --all-files" -p pre-commit || true
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: "[automation] update niv dependencies"
        title: "[automation] update niv dependencies"
        branch: "automation/update-niv-dependencies"
        token: "${{ secrets.PR_TOKEN }}"
        delete-branch: true
